### PR TITLE
Feature/better response handling

### PR DESCRIPTION
**Pull request by craigp**
Just cleaned up some of the code and used structs for requests, responses and messages to expose all the possible parameters, fixed up the docs for publishing to hex. Some additional minor code changes and a patch version bump.

### CODE REVIEW

**Comment by craigp** [comment]
I don't seem to have the rights to create the `Ready for review` label, could you please add it @sinakarimi

**Comment by sinakarimi** [comment]
I've added the label, and also given you admin permission :)

**Comment by craigp** [comment]
Can we merge this in?

**Comment by sinakarimi** [comment]
👍

**Pull request merged**
