### PR TITLE
Basic send request

### PR DESCRIPTION
**Pull request by craigp**
This isn't complete but it's a start - 100% test coverage, for whatever that's worth. It only covers the basic send options, and only handles responses with a single nested message at the moment. We might end up removing the app setup for it, depending on whether or not we end up using any processes internally.

### CODE REVIEW

**Comment by sinakarimi** [comment]
Awesome! This is looking like a great start. Once the merge conflicts are fixed I'll merge this in and probably transfer ownership to the KindyNowApp account. We'll take the conversation to Trello to discuss what's left to do.

**Comment by craigp** [comment]
Fixed the merge conflicts - I removed the old `API` class, since I'd done that implementation in the `SMS.Request`, we can put it back later if we want a higher level API object to deal with.

**Comment by craigp** [comment]
I can't add labels on this repo, but I think this is ready for review/merge

**Comment by sinakarimi** [comment]
👍

**Pull request merged**
